name: zig_btree

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: zig_btree

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: latest

      - name: Run tests
        run: zig build test
